#ifndef SCRIBE_ERROR_H
#define SCRIBE_ERROR_H

enum ScribeError {
	SCRIBE_OK = 0,

	SCRIBE_ERR_INVALID_ARGUMENT,
	SCRIBE_ERR_UNEXPECTED_ARGUMENT,

	SCRIBE_ERR_MISSING_OPTION_VALUE,
	SCRIBE_ERR_UNKNOWN_OPTION,

	SCRIBE_ERR_MISSING_COMMAND,
	SCRIBE_ERR_UNKNOWN_COMMAND,

	SCRIBE_ERR_ROOT_CREATE_FAILED,
	SCRIBE_ERR_DUPLICATE_MIGRATION_VERSION,

	SCRIBE_ERR_SQL,
	SCRIBE_ERR_INVALID_MIGRATION_PLAN,

	SCRIBE_ERR_OUT_OF_MEMORY,
	SCRIBE_ERR_IO
};

#endif // SCRIBE_ERROR_H
